[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "violet" 

# Background color for the main content area.
# backgroundColor = "darkblue"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "gray"

# Color used for almost all text.
# textColor = "white"